### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by Aterfax** [sonicsnes/node-gamedig#103]
Running into an error while trying to use gamedig in either mode, not sure why.

```
/usr/local/lib/node_modules/gamedig/lib/index.js:10
    async query(userOptions) {
          ^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/gamedig/bin/gamedig.js:4:15)
```

Debian 8 on Node v6.14.4

**Comment by Aterfax** [comment]
My bad, looks like it needs node 8 to run properly.

Closing.

**Comment by sonicsnes** [comment]
If you require node 6 support, node-gamedig 1 should work (although without the latest updates and fixes) 😄
