### ISSUE TITLE
Ark: Survival Evolved not working for me

### ISSUE THREAD

**Issue by NightYoshi370** [sonicsnes/node-gamedig#125]
So I am making a Discord.JS bot called Yamamura and I wanted to implement gaming servers into it. Unfortunately, when trying to implement a ARK: Survivor Evolved command, the bot will not respond, even though all the other commands work.

This is my javascript code:

```js
let IP = '147.135.120.153:7783'
let embed = this.client.util.embed()

    IP = IP.split(':');
    let fullIP = IP.join(':')

    let host = IP[0];
    let port = IP[1] ? parseInt(IP[1]) : 27015;

    console.log(host, port, IP, fullIP)
    try {
      let data = await source.query({
        type: 'arkse',
        host: host,
        port: port
      });

      embed
        .setColor("BLUE")
        .setTitle(data.name)
        .setDescription('[ARK: Survival Evolved](https://store.steampowered.com/app/346110/)')
        .addInline('Server IP', `\`${host}:${port}\``)
        .addInline('Players', `${data.players.length}/${data.maxplayers}`)
        .addField('Map', data.map)
        .setImage('https://cache.gametracker.com/server_info/'+host+':'+port+'/b_560_95_1.png')

      if (data.players.length) {
        let players = [];
        let scores = [];
        let pings = [];
        for (var player of data.players) {
          players.push(player.name);
          scores.push(player.frags);
          pings.push(`${player.ping}ms`);
        }

        embed
          .addInline('Player', '````http\n'+players.join('\n')+'```')
          .addInline('Score', '```http\n'+scores.join('\n')+'```')
          .addInline('Ping', '```http\n'+pings.join('\n')+'```')
          .addField('Join', `<steam://connect/${host}:${port}>`)
      }

      if (data.password) {
        embed.setFooter(`Private Server`, 'https://cdn.discordapp.com/attachments/371531450182402081/573395978833494027/lock.png')
      }

      message.channel.send({embed});
    } catch (e) {
      if (e.toString().includes('UDP Watchdog Timeout')) {
        embed
          .setColor("#FF0000")
          .setTitle("Error: Game server offline")
          .setDescription(`<@${message.author.id}>, please try connecting to ${fullIP} at a later date`)
          .setYamamuraCredits(true)

        message.util.send({embed});
      } else {
        console.log(e);
      }
    }
```

This is my console:
```
147.135.120.153 7783 [ '147.135.120.153', '7783' ] 147.135.120.153:7783

Error: Failed all 1 attempts

    at QueryRunner.run (/rbd/pnpm-volume/6959811c-1d7b-489f-b1f0-281ae0d8936c/node_modules/.registry.npmjs.org/gamedig/2.0.14/node_modules/gamedig/lib/QueryRunner.js:88:21)

Attempt #1 - Port=7783 Retry=0:

Error: UDP - Timed out after 2000ms

    at Timeout.setTimeout (/rbd/pnpm-volume/6959811c-1d7b-489f-b1f0-281ae0d8936c/node_modules/.registry.npmjs.org/gamedig/2.0.14/node_modules/gamedig/lib/Promises.js:7:25)

    at ontimeout (timers.js:436:11)

    at tryOnTimeout (timers.js:300:5)

    at listOnTimeout (timers.js:263:5)

    at Timer.processTimers (timers.js:223:10)
```

I do not believe that this is an issue on my end, considering that other commands with similar code work. If there is any further things I need to do, please let me know

**Comment by NightYoshi370** [comment]
This is the server I tried accessing BTW: https://arkservers.net/server/147.135.120.153:27021

**Comment by sonicsnes** [comment]
Gamedig attempts to find the query port automatically, but this is not possible in all cases (when the offset is not deterministic). You are passing port = 7783, but you need to pass 27021.
