### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by onrdrsy** [sonicsnes/node-gamedig#134]
When I update the module to version 2.0.14 I get the following error string.

It works when I go back to version 1.0.49. I don't know what to do.

```(node:14008) UnhandledPromiseRejectionWarning: Error: Failed all 1 attempts

    at QueryRunner.run (/rbd/pnpm-volume/ae1999ae-4082-4f5e-8ac6-31f44333aee1/node_modules/.registry.npmjs.org/gamedig/2.0.14/node_modules/gamedig/lib/QueryRunner.js:88:21)

    at <anonymous>

Attempt #1 - Port=27015 Retry=0:

Error: getaddrinfo ENOTFOUND none

    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)

(node:14008) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

(node:14008) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by sonicsnes** [comment]
Can you provide a code snippet of how you are calling gamedig?
