### ISSUE TITLE
Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by TheRealKizu** [sonicsnes/node-gamedig#154]
Error: Failed all 1 attempts
    at QueryRunner.run (/home/therealkizu/Alaia/node_modules/gamedig/lib/QueryRunner.js:88:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Attempt #1 - Port=19132 Retry=0:
TypeError: Cannot read property 'match' of undefined
    at DnsResolver.isIp (/home/therealkizu/Alaia/node_modules/gamedig/lib/DnsResolver.js:17:23)
    at DnsResolver.resolve (/home/therealkizu/Alaia/node_modules/gamedig/lib/DnsResolver.js:29:17)
    at Minecraft.runOnce (/home/therealkizu/Alaia/node_modules/gamedig/protocols/core.js:71:53)
    at Minecraft.runOnceSafe (/home/therealkizu/Alaia/node_modules/gamedig/protocols/core.js:50:34)
    at QueryRunner._attempt (/home/therealkizu/Alaia/node_modules/gamedig/lib/QueryRunner.js:99:27)
    at QueryRunner.run (/home/therealkizu/Alaia/node_modules/gamedig/lib/QueryRunner.js:80:39)
    at Gamedig.query (/home/therealkizu/Alaia/node_modules/gamedig/lib/index.js:11:39)
    at Function.query (/home/therealkizu/Alaia/node_modules/gamedig/lib/index.js:19:44)
    at Object.run (/home/therealkizu/Alaia/commands/minecraft/mcpe.js:22:17)
    at Client.client.on (/home/therealkizu/Alaia/alaia.js:118:23)
    at Client.emit (events.js:203:15)
    at MessageCreateHandler.handle (/home/therealkizu/Alaia/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/home/therealkizu/Alaia/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:105:65)
    at WebSocketConnection.onPacket (/home/therealkizu/Alaia/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/home/therealkizu/Alaia/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
    at WebSocket.onMessage (/home/therealkizu/Alaia/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:198:13)
    at Receiver.receiverOnMessage (/home/therealkizu/Alaia/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:198:13)
    at Receiver.dataMessage (/home/therealkizu/Alaia/node_modules/ws/lib/receiver.js:422:14)
    at Receiver.getData (/home/therealkizu/Alaia/node_modules/ws/lib/receiver.js:352:17)
    at Receiver.startLoop (/home/therealkizu/Alaia/node_modules/ws/lib/receiver.js:138:22)

**Comment by TheRealKizu** [comment]
Self-fixed.
