### ISSUE TITLE
Getting an error when trying to use an IP.

### ISSUE THREAD

**Issue by tzahush** [sonicsnes/node-gamedig#32]
Hello, i am getting this following error:
\node_modules\gamedig\protocols\core.js:103
                                if(options.host.match(/\d+\.\d+\.\d+\.\d+/)) {
                                                ^
TypeError: undefined is not a function
    at module.exports.Class.extend.start.async.series.offset (***node_modules\gamedig\protocols\core.js:103:21)
    at ***node_modules\gamedig\node_modules\async\lib\async.js:607:21
    at ***node_modules\gamedig\node_modules\async\lib\async.js:246:17
    at async.eachSeries.iterate (***node_modules\gamedig\node_modules\async\lib\async.js:146:13)
    at async.eachSeries (***node_modules\gamedig\node_modules\async\lib\async.js:162:9)
    at _asyncMap (***node_modules\gamedig\node_modules\async\lib\async.js:245:13)
    at Object.doSeries [as mapSeries] (***node_modules\gamedig\node_modules\async\lib\async.js:228:23)
    at Object.async.series (***node_modules\gamedig\node_modules\async\lib\async.js:605:19)
    at Class.module.exports.Class.extend.start (***node_modules\gamedig\protocols\core.js:99:9)
    at ***node_modules\gamedig\lib\index.js:72:10
    at process._tickCallback (node.js:355:11)

I am not sure if this is a problem just for me.

**Comment by tzahush** [comment]
Made the IP to Integer, ruined it.
