### ISSUE TITLE
Strict mode

### ISSUE THREAD

**Issue by Samuell1** [sonicsnes/node-gamedig#67]
Hey, i getting this error using graph.cool . Looks like there is missing strict mode

```
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:373:25)
at Module._compile (/data/sandbox/lib/module.js:127:21)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at WebtaskModule.require (/data/sandbox/lib/module.js:101:19)
at require (/data/sandbox/lib/module.js:136:21)
at Object.<anonymous> (/data/io/2a7475ab28884c25887bd992c4d7b708/webtask.js:1:79)
at WebtaskModule.compileWebtask (/data/sandbox/lib/module.js:95:34)
```

**Comment by sonicsnes** [comment]
node-gamedig 1.0 requires node.js 6.0 -- these es6 features were only partially implemented, or required strict mode in previous node.js versions.
